using UnityEngine;
using System.Collections;
using UnityEditor;

#pragma warning disable 0168 // variable declared but not used.
#pragma warning disable 0219 // variable assigned but not used.
#pragma warning disable 0414 // private field assigned but not used.

[CustomEditor(typeof(DKUMAData))]
public class DKUMADataInspector : Editor {
	DKUMAData _DKUMAData;
	bool ViewInspector = false;


	void OnEnable (){
		_DKUMAData = (DKUMAData)target;
	}

	public override void OnInspectorGUI()
	{
		EditorGUILayout.HelpBox("This component is required by the DK UMA Avatar. " +
			"It is used for the generation of the avatar.", UnityEditor.MessageType.None);
		
		EditorGUILayout.HelpBox("It contains the Packed DK streamed avatar used for a network use of the DK UMA Avatars.", UnityEditor.MessageType.None);

		EditorGUILayout.HelpBox("It also contains the DK DNA list of the avatar. This DNA is sent to the UMA avatar after the avatar to be generated by the UMA Engine at runtime.", UnityEditor.MessageType.None);
		ViewInspector = EditorGUILayout.Toggle ( "View Inspector",ViewInspector);
		if ( ViewInspector ) DrawDefaultInspector();
	}

}
